version: '3.8'

volumes:
  postgres:
  postgres-data:

services:
  postgres:
    image: postgres:13
    container_name: postgres_cms_1
    restart: unless-stopped
    environment:
      - POSTGRES_DB=cms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./.postgres-data/db:/var/lib/postgresql/data
    ports:
      - 5433:5433
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 3s
      retries: 10

  grpc-server:
    build:
      context: .
    command: ["./grpc-server"]
    container_name: grpc-server
    hostname: grpc-server
    # networks:
    #   - cms
    ports:
      - 8000:8000
    environment:
      - PGUSER=${PGUSER:-postgres}
      - PGPASSWORD=${PGPASSWORD:?database password not set}
      - PGHOST=${PGHOST:-db}
      - PGPORT=${PGPORT:-5433}
      - PGDATABASE=${PGDATABASE:-cms}
      - PGSSLMODE=${PGSSLMODE:-disable}
      - HTTP_PORT=${HTTP_PORT:-8080}
      - CURRENT_ENV=${CURRENT_ENV:-stage}
      - LOG_PATH=${LOG_PATH:-./tmp/}
    deploy:
      restart_policy:
        condition: on-failure
        
# networks:
#   cms:
#     external: true
