// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: core/v1/article/article.proto

package article

import (
	meta "cms/protocgen/global/meta"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	AuthorId      string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"` // Assuming author_id is a string, can be changed to int64 if needed
	Tag           []string               `protobuf:"bytes,5,rep,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_core_v1_article_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_article_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_core_v1_article_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Article) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Article) GetTag() []string {
	if x != nil {
		return x.Tag
	}
	return nil
}

type CreateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleRequest) Reset() {
	*x = CreateArticleRequest{}
	mi := &file_core_v1_article_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleRequest) ProtoMessage() {}

func (x *CreateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_article_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleRequest.ProtoReflect.Descriptor instead.
func (*CreateArticleRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_article_article_proto_rawDescGZIP(), []int{1}
}

func (x *CreateArticleRequest) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type CreateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateArticleResponse) Reset() {
	*x = CreateArticleResponse{}
	mi := &file_core_v1_article_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateArticleResponse) ProtoMessage() {}

func (x *CreateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_article_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateArticleResponse.ProtoReflect.Descriptor instead.
func (*CreateArticleResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_article_article_proto_rawDescGZIP(), []int{2}
}

func (x *CreateArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *CreateArticleResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type GetArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleRequest) Reset() {
	*x = GetArticleRequest{}
	mi := &file_core_v1_article_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleRequest) ProtoMessage() {}

func (x *GetArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_article_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleRequest.ProtoReflect.Descriptor instead.
func (*GetArticleRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_article_article_proto_rawDescGZIP(), []int{3}
}

func (x *GetArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetArticleResponse) Reset() {
	*x = GetArticleResponse{}
	mi := &file_core_v1_article_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArticleResponse) ProtoMessage() {}

func (x *GetArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_article_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArticleResponse.ProtoReflect.Descriptor instead.
func (*GetArticleResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_article_article_proto_rawDescGZIP(), []int{4}
}

func (x *GetArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *GetArticleResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type ListArticlesRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Pagination    *meta.PaginationRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Query         *meta.FilterRequest     `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesRequest) Reset() {
	*x = ListArticlesRequest{}
	mi := &file_core_v1_article_article_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesRequest) ProtoMessage() {}

func (x *ListArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_article_article_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesRequest.ProtoReflect.Descriptor instead.
func (*ListArticlesRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_article_article_proto_rawDescGZIP(), []int{5}
}

func (x *ListArticlesRequest) GetPagination() *meta.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListArticlesRequest) GetQuery() *meta.FilterRequest {
	if x != nil {
		return x.Query
	}
	return nil
}

type ListArticlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Articles      []*Article             `protobuf:"bytes,1,rep,name=articles,proto3" json:"articles,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListArticlesResponse) Reset() {
	*x = ListArticlesResponse{}
	mi := &file_core_v1_article_article_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArticlesResponse) ProtoMessage() {}

func (x *ListArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_article_article_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArticlesResponse.ProtoReflect.Descriptor instead.
func (*ListArticlesResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_article_article_proto_rawDescGZIP(), []int{6}
}

func (x *ListArticlesResponse) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ListArticlesResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type UpdateArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleRequest) Reset() {
	*x = UpdateArticleRequest{}
	mi := &file_core_v1_article_article_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleRequest) ProtoMessage() {}

func (x *UpdateArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_article_article_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleRequest.ProtoReflect.Descriptor instead.
func (*UpdateArticleRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_article_article_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateArticleRequest) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

type UpdateArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateArticleResponse) Reset() {
	*x = UpdateArticleResponse{}
	mi := &file_core_v1_article_article_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateArticleResponse) ProtoMessage() {}

func (x *UpdateArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_article_article_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateArticleResponse.ProtoReflect.Descriptor instead.
func (*UpdateArticleResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_article_article_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *UpdateArticleResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DeleteArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleRequest) Reset() {
	*x = DeleteArticleRequest{}
	mi := &file_core_v1_article_article_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleRequest) ProtoMessage() {}

func (x *DeleteArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_article_article_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArticleRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_article_article_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteArticleRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	Meta          *meta.Meta             `protobuf:"bytes,2,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArticleResponse) Reset() {
	*x = DeleteArticleResponse{}
	mi := &file_core_v1_article_article_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArticleResponse) ProtoMessage() {}

func (x *DeleteArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_article_article_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArticleResponse.ProtoReflect.Descriptor instead.
func (*DeleteArticleResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_article_article_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteArticleResponse) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *DeleteArticleResponse) GetMeta() *meta.Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

var File_core_v1_article_article_proto protoreflect.FileDescriptor

const file_core_v1_article_article_proto_rawDesc = "" +
	"\n" +
	"\x1dcore/v1/article/article.proto\x1a\x16global/meta/meta.proto\"x\n" +
	"\aArticle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12\x10\n" +
	"\x03tag\x18\x05 \x03(\tR\x03tag\":\n" +
	"\x14CreateArticleRequest\x12\"\n" +
	"\aarticle\x18\x01 \x01(\v2\b.ArticleR\aarticle\"V\n" +
	"\x15CreateArticleResponse\x12\"\n" +
	"\aarticle\x18\x01 \x01(\v2\b.ArticleR\aarticle\x12\x19\n" +
	"\x04meta\x18\x02 \x01(\v2\x05.MetaR\x04meta\"#\n" +
	"\x11GetArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"S\n" +
	"\x12GetArticleResponse\x12\"\n" +
	"\aarticle\x18\x01 \x01(\v2\b.ArticleR\aarticle\x12\x19\n" +
	"\x04meta\x18\x02 \x01(\v2\x05.MetaR\x04meta\"o\n" +
	"\x13ListArticlesRequest\x122\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x12.PaginationRequestR\n" +
	"pagination\x12$\n" +
	"\x05query\x18\x02 \x01(\v2\x0e.FilterRequestR\x05query\"W\n" +
	"\x14ListArticlesResponse\x12$\n" +
	"\barticles\x18\x01 \x03(\v2\b.ArticleR\barticles\x12\x19\n" +
	"\x04meta\x18\x03 \x01(\v2\x05.MetaR\x04meta\":\n" +
	"\x14UpdateArticleRequest\x12\"\n" +
	"\aarticle\x18\x01 \x01(\v2\b.ArticleR\aarticle\"V\n" +
	"\x15UpdateArticleResponse\x12\"\n" +
	"\aarticle\x18\x01 \x01(\v2\b.ArticleR\aarticle\x12\x19\n" +
	"\x04meta\x18\x02 \x01(\v2\x05.MetaR\x04meta\"&\n" +
	"\x14DeleteArticleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"V\n" +
	"\x15DeleteArticleResponse\x12\"\n" +
	"\aarticle\x18\x01 \x01(\v2\b.ArticleR\aarticle\x12\x19\n" +
	"\x04meta\x18\x02 \x01(\v2\x05.MetaR\x04meta2\xc4\x02\n" +
	"\x0eArticleService\x12>\n" +
	"\rCreateArticle\x12\x15.CreateArticleRequest\x1a\x16.CreateArticleResponse\x125\n" +
	"\n" +
	"GetArticle\x12\x12.GetArticleRequest\x1a\x13.GetArticleResponse\x12;\n" +
	"\fListArticles\x12\x14.ListArticlesRequest\x1a\x15.ListArticlesResponse\x12>\n" +
	"\rUpdateArticle\x12\x15.UpdateArticleRequest\x1a\x16.UpdateArticleResponse\x12>\n" +
	"\rDeleteArticle\x12\x15.DeleteArticleRequest\x1a\x16.DeleteArticleResponseB\x1fZ\x1dcms/protocgen/core/v1/articleb\x06proto3"

var (
	file_core_v1_article_article_proto_rawDescOnce sync.Once
	file_core_v1_article_article_proto_rawDescData []byte
)

func file_core_v1_article_article_proto_rawDescGZIP() []byte {
	file_core_v1_article_article_proto_rawDescOnce.Do(func() {
		file_core_v1_article_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_article_article_proto_rawDesc), len(file_core_v1_article_article_proto_rawDesc)))
	})
	return file_core_v1_article_article_proto_rawDescData
}

var file_core_v1_article_article_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_core_v1_article_article_proto_goTypes = []any{
	(*Article)(nil),                // 0: Article
	(*CreateArticleRequest)(nil),   // 1: CreateArticleRequest
	(*CreateArticleResponse)(nil),  // 2: CreateArticleResponse
	(*GetArticleRequest)(nil),      // 3: GetArticleRequest
	(*GetArticleResponse)(nil),     // 4: GetArticleResponse
	(*ListArticlesRequest)(nil),    // 5: ListArticlesRequest
	(*ListArticlesResponse)(nil),   // 6: ListArticlesResponse
	(*UpdateArticleRequest)(nil),   // 7: UpdateArticleRequest
	(*UpdateArticleResponse)(nil),  // 8: UpdateArticleResponse
	(*DeleteArticleRequest)(nil),   // 9: DeleteArticleRequest
	(*DeleteArticleResponse)(nil),  // 10: DeleteArticleResponse
	(*meta.Meta)(nil),              // 11: Meta
	(*meta.PaginationRequest)(nil), // 12: PaginationRequest
	(*meta.FilterRequest)(nil),     // 13: FilterRequest
}
var file_core_v1_article_article_proto_depIdxs = []int32{
	0,  // 0: CreateArticleRequest.article:type_name -> Article
	0,  // 1: CreateArticleResponse.article:type_name -> Article
	11, // 2: CreateArticleResponse.meta:type_name -> Meta
	0,  // 3: GetArticleResponse.article:type_name -> Article
	11, // 4: GetArticleResponse.meta:type_name -> Meta
	12, // 5: ListArticlesRequest.pagination:type_name -> PaginationRequest
	13, // 6: ListArticlesRequest.query:type_name -> FilterRequest
	0,  // 7: ListArticlesResponse.articles:type_name -> Article
	11, // 8: ListArticlesResponse.meta:type_name -> Meta
	0,  // 9: UpdateArticleRequest.article:type_name -> Article
	0,  // 10: UpdateArticleResponse.article:type_name -> Article
	11, // 11: UpdateArticleResponse.meta:type_name -> Meta
	0,  // 12: DeleteArticleResponse.article:type_name -> Article
	11, // 13: DeleteArticleResponse.meta:type_name -> Meta
	1,  // 14: ArticleService.CreateArticle:input_type -> CreateArticleRequest
	3,  // 15: ArticleService.GetArticle:input_type -> GetArticleRequest
	5,  // 16: ArticleService.ListArticles:input_type -> ListArticlesRequest
	7,  // 17: ArticleService.UpdateArticle:input_type -> UpdateArticleRequest
	9,  // 18: ArticleService.DeleteArticle:input_type -> DeleteArticleRequest
	2,  // 19: ArticleService.CreateArticle:output_type -> CreateArticleResponse
	4,  // 20: ArticleService.GetArticle:output_type -> GetArticleResponse
	6,  // 21: ArticleService.ListArticles:output_type -> ListArticlesResponse
	8,  // 22: ArticleService.UpdateArticle:output_type -> UpdateArticleResponse
	10, // 23: ArticleService.DeleteArticle:output_type -> DeleteArticleResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_core_v1_article_article_proto_init() }
func file_core_v1_article_article_proto_init() {
	if File_core_v1_article_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_article_article_proto_rawDesc), len(file_core_v1_article_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_article_article_proto_goTypes,
		DependencyIndexes: file_core_v1_article_article_proto_depIdxs,
		MessageInfos:      file_core_v1_article_article_proto_msgTypes,
	}.Build()
	File_core_v1_article_article_proto = out.File
	file_core_v1_article_article_proto_goTypes = nil
	file_core_v1_article_article_proto_depIdxs = nil
}
